# Generated by Django 5.1.3 on 2024-11-16 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0003_alter_timetable_class_name_alter_timetable_subject_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetable',
            name='year',
            field=models.IntegerField(default=1),
        ),
    ]
