# Generated by Django 5.1.3 on 2024-11-16 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0004_timetable_year'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Class',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='subject',
        ),
        migrations.DeleteModel(
            name='Timeslot',
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
        migrations.DeleteModel(
            name='Teacher',
        ),
    ]
