# Generated by Django 5.1.3 on 2024-11-16 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0005_delete_class_remove_teacher_subject_delete_timeslot_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('year', models.IntegerField()),
                ('class_name', models.CharField(max_length=50)),
            ],
        ),
    ]
