# Generated by Django 5.1.3 on 2024-11-16 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0006_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetable',
            name='students',
            field=models.ManyToManyField(related_name='timetables', to='timetable.student'),
        ),
    ]
